import type { Metadata } from "next";

import Navigation from "@/components/Navigation";
import "./globals.css";
import SessionProvider from "./provider";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <Navigation></Navigation>
          {children}
          <Footer></Footer>
        </SessionProvider>
      </body>
    </html>
  );
}
